### ISSUE TITLE
tensorflow 2.4.1

### ISSUE THREAD

**Issue by luantunez** [henrysky/astroNN#13]
Hello, thank you for your work!
Does astroNN work with tensorflow 2.4.1?
Because whenever I import a module I get

cannot import name 'get_default_session' from 'tensorflow' 

For example I am trying to do 

from astroNN.models.apogee_models import ApogeeBCNN

thank you in advance, Lucia

**Comment by henrysky** [comment]
Yes astroNN is currently being tested against tf2.3 tf2.4 and the unreleased tf2.5.

I dont think I use `get_default_session()` anywhere anymore as everything is eagerly executed now. So please use the latest master branch.

**Comment by luantunez** [comment]
thank you for your quick response, I will get the latest version.

**Comment by luantunez** [comment]
I now could get the latest version by installing with

$ git clone --depth=1 https://github.com/henrysky/astroNN
$ python setup.py install

and it is working!

Thank you
